# Generated by Django 4.2.6 on 2025-08-06 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servidores', '0004_remove_servidor_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descanso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Férias', 'Férias'), ('Afastamento', 'Afastamento'), ('Folga compensatória', 'Folga compensatória'), ('Outros', 'Outros')], max_length=30)),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descansos', to='servidores.servidor')),
            ],
            options={
                'verbose_name': 'Descanso',
                'verbose_name_plural': 'Descansos',
                'ordering': ['-inicio'],
            },
        ),
    ]
