# Generated by Django 4.2.6 on 2025-08-11 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='perfil',
            field=models.CharField(blank=True, choices=[('gerente', 'Gerente'), ('supervisor', 'Supervisor'), ('unidade', 'Unidade')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PerfilPolitica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('permissoes', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
            options={
                'permissions': [('manage_policies', 'Pode gerenciar perfis e políticas')],
            },
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='perfil_politica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='organizacao.perfilpolitica'),
        ),
    ]
