# Generated by Django 5.2.4 on 2025-08-01 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0001_initial'),
        ('servidores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servidores', to='organizacao.unidade'),
        ),
    ]
