# Generated by Django 4.2.6 on 2025-08-05 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servidores', '0002_servidor_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='servidores', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
