# Generated by Django 4.2.6 on 2025-08-05 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0003_servidor_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servidor',
            name='usuario',
        ),
    ]
