# Generated by Django 4.2.6 on 2025-08-08 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atividades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('quantidade_realizada', models.PositiveIntegerField(default=0)),
                ('prazo', models.DateField()),
                ('observacoes', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('nova', 'Nova'), ('atribuida', 'Atribuída'), ('concluida', 'Concluída'), ('atrasada', 'Atrasada'), ('vencida', 'Vencida')], default='nova', max_length=20)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atividades.atividade')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metas_criadas', to=settings.AUTH_USER_MODEL)),
                ('destinatario_supervisao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metas_recebidas', to='organizacao.supervisao')),
                ('destinatario_unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metas_unidade', to='organizacao.unidade')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
            },
        ),
    ]
